### ISSUE TITLE
Endpoints für User Management

### ISSUE THREAD

**Issue by MysterionAutotronic** [amplimindcc/backend#14]
1. listUsers: alle User zurückgeben mit email: string und admin: boolean
2. addUser: User hinzufügen mit email: string und admin: boolean
3. deleteUser: User löschen mit email: string
4. modifyUser: User elevate oder demote mit email: string und admin: boolean (Wert aktualisieren)

**Comment by Stefan7400** [comment]
@MysterionAutotronic 
listUsers (gibts schon /v1/admin/fetch/users/all) liefert alle notwendigen daten fürs frotend
und addUser passiert über den /invite endpoint (dazu gibts ein extra ticket schon)
