### ISSUE TITLE
Delete Project Endpoint

### ISSUE THREAD

**Issue by SrNski** [amplimindcc/backend#25]
Im AdminController einen Endpoint hinzufügen um ein Project zu löschen (löschen via id des Projects)

**Comment by Stefan7400** [comment]
Eins wäre noch wichtig ein Project darf nicht gelöscht werden wenn es aktuell von einer Aufgabe verwendet wird, welche noch nicht abgeschlossen / oder die Abgabefrist noch nicht erreicht hat
