### ISSUE TITLE
Password Check

### ISSUE THREAD

**Issue by MysterionAutotronic** [amplimindcc/backend#86]
Criteria
- at least 8 characters long
- contains at least one special character, frontend checks this with: `/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/`

**Comment by ris5266** [comment]
@MysterionAutotronic wollt ihr auch eine validierung, dass mindestens eine zahl im password drinnen ist?

**Comment by MysterionAutotronic** [comment]
Brauchen wir denke ich nicht. Wir haben einen Password Strength Meter drin - dann kann der Nutzer selbst entscheiden ob ihm das sicher genug ist - Sonderzeichen und 8 Character eliminieren schon mal die 10k NCSC most common Passwörter
